import datetime
from mongoengine.document import Document, EmbeddedDocument

from mongoengine.fields import DateTimeField, DictField, EmbeddedDocumentField, FileField, ListField, StringField


class Info(EmbeddedDocument):  # generated by cuckoo sandbox
    package = StringField(required=True)  # exe, elf...
    platform = StringField(required=True)  # linux/win7/...


class Target(EmbeddedDocument):  # generated by cuckoo sandbox
    md5 = StringField(required=True)
    urls = ListField(StringField())
    name = StringField(required=True)


class Static(EmbeddedDocument):  # generated by cuckoo sandbox
    strings = ListField(StringField(), required=True)
    pe_imports = ListField()
    pe_exports = ListField()
    pe_resources = ListField()
    pe_sections = ListField(required=True)
    pe_timestamp = DateTimeField(
        default=datetime.datetime.utcnow, required=True)  # 出现时间, 默认为当前时间


class Behavior(EmbeddedDocument):  # generated by cuckoo sandbox 
    generic = ListField()
    file_opened = ListField(StringField())
    file_created = ListField(StringField())
    file_recreated = ListField(StringField())
    file_exists = ListField(StringField())
    file_read = ListField(StringField())
    file_written = ListField(StringField())
    file_failed = ListField(StringField())
    directory_created = ListField(StringField())
    dll_loaded = ListField(StringField())
    mutex = ListField(StringField())
    regkey_written = ListField(StringField())
    regkey_opened = ListField(StringField())
    regkey_read = ListField(StringField())
    command_line = ListField(StringField())
    guid = ListField(StringField())
    extracted = ListField()
    dropped = ListField()
    processes = ListField()
    processtree = ListField()


class Local(EmbeddedDocument):  # generated by local analysis
    asm_file = FileField(required=True)  # 只包含text区段
    bytes_file = FileField(required=True)  # 只包含text区段
    bmp_file = FileField(required=True)  # 包含text, data, rdata区段
    malware_classification_resnet34 = DictField(
        required=True)
    malware_sim_doc2vec = ListField(
        required=True)


class Feature(Document):
    task_id = StringField(primary_key=True)  # 任务id
    upload_time = DateTimeField(default=datetime.datetime.utcnow)  # 样本上传时间
    upload = FileField(required=True)  # 样本文件

    info = EmbeddedDocumentField(Info, required=True)  # 文件基本信息
    target = EmbeddedDocumentField(Target, required=True)  # 文件指纹信息
    static = EmbeddedDocumentField(Static, required=True)  # 静态分析结果
    network = DictField(required=True)  # 网络分析结果
    debug = DictField(required=True)  # cuckoo debug info
    apt_family = StringField(default="未知")  # APT组织

    local = EmbeddedDocumentField(Local, required=True)  # model analysis

    # optional    
    _buffer = ListField()  # 缓冲区分析信息 
    procmemory = ListField()  # 内存分布信息, optional
    behavior = EmbeddedDocumentField(Behavior)  # 系统行为信息, optional
    signatures = ListField()  # signature信息, optional

    meta = {'collection': 'features'}  # 存储在名为feature的collection中
